# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#  "." am Anfang bezeichnet den Top-Level Namensraum

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pgadmin.name }}-pgadmin-volume
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.pgadmin.name }}-pgadmin
    app.kubernetes.io/instance: {{ .Values.pgadmin.name }}-pgadmin
    app.kubernetes.io/version: {{ .Values.pgadmin.version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank-administration
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 512Ki
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/pgadmin
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pgadmin.name }}-pgadmin4-volume
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.pgadmin.name }}-pgadmin4
    app.kubernetes.io/instance: {{ .Values.pgadmin.name }}-pgadmin4
    app.kubernetes.io/version: {{ .Values.pgadmin.version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank-administration
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 64Ki
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/pgadmin4
    type: Directory
