// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
//

### Suche aller Lieder
GET {{restUrl}}

### Suche mit vorhandener Lied-ID
GET {{restUrl}}/1

### Suche mit vorhandener Lied-ID und Versionsnummer
GET {{restUrl}}/1
If-None-Match: "0"

### Suche mit vorhandener Lied-ID und falscher Versionsnummer
GET {{restUrl}}/1
If-None-Match: 0

### Suche mit nicht-vorhandener Lied-ID
GET {{restUrl}}/999999

### Suche mit vorhandenem Titel
GET {{restUrl}}?titel=a

### Suche mit nicht-vorhandenem Titel
GET {{restUrl}}?titel=xxx

### Suche mit vorhandenem Schlagwort "Pop"
GET {{restUrl}}?Pop=true

### Suche mit nicht-vorhandener Property
GET {{restUrl}}?php=true

### Suche mit gueltiger Liedart
GET {{restUrl}}?art=CD

### Suche mit gueltigem Rating
GET {{restUrl}}?rating=1
