# Copyright (C) 2022 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

#  "." am Anfang bezeichnet den Top-Level Namensraum

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.name" . }}-data-volume
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}-data
    app.kubernetes.io/instance: {{ include "postgres.name" . }}-data
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/data
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.name" . }}-conf-volume
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}-conf
    app.kubernetes.io/instance: {{ include "postgres.name" . }}-conf
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 128Ki
  accessModes: [ReadOnlyMany]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/postgresql.conf
    type: File

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.name" . }}-tablespace-volume
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}-tablespace
    app.kubernetes.io/instance: {{ include "postgres.name" . }}-tablespace
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/tablespace
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "postgres.name" . }}-run-volume
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}-run
    app.kubernetes.io/instance: {{ include "postgres.name" . }}-run
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "postgres.chart" . }}
spec:
  capacity:
    storage: 128Ki
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/postgres/run
    type: Directory
