' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package lied {
  package entity {
    class Lied
  }

  package service #DDDDDD {
    class LiedInvalid
    class TitelExists
    class VersionInvalid
    class VersionOutdated

    class LiedWriteService << control >> <<@Injectable()>> {
      + async create(lied: Lied): Promise<string|LiedInvalid|TitelExists|IsbnExists>
      + async update(id: string, lied: Lied, version: string): Promise<number|LiedInvalid|TitelExists|IsbnExists|VersionInvalid|VersionOutdated>
      + async delete(id: string): Promise<boolean>
    }

    LiedWriteService o--> "1" LiedValidationService: validationService
    LiedWriteService o--> "1" LiedReadService: readService
    LiedWriteService o--> "1" Repository: @InjectRepository repo
    LiedWriteService o--> "1" MailService: mailService

    LiedWriteService .up.> Injectable
    LiedWriteService .up.> InjectRepository

    LiedWriteService .up.> Promise
    LiedWriteService ..> Lied
    LiedWriteService .up.> LiedInvalid
    LiedWriteService .up.> TitelExists
    LiedWriteService .up.> VersionInvalid
    LiedWriteService .up.> VersionOutdated

    LiedInvalid .up[hidden].> Lied
    Lied .up[hidden].> Promise
    Lied .up[hidden].> Injectable
    Lied .up[hidden].> InjectRepository
    TitelExists .up[hidden].> Lied
    LiedValidationService .[hidden].> Repository
    LiedValidationService .[hidden].> MailService
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
