// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

// siehe auch https://studio.apollographql.com/sandbox/explorer

### Suche id, version und titel von allen Liedern
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  lieder {
    id
    titel
    version
    rating
    art
    datum
    schlagwoerter
    kuenstler {
      name
    }
  }
}

### Suche isbn, version, art und titel von einem Lied mit vorhandener Lied-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "1") {
  lied(id: $id) {
    titel
    version
    rating
    art
    datum
    schlagwoerter
    kuenstler {
      name
    }
  }
}

{
  "id": "1"
}

### Suche titel von einem Lied mit nicht-vorhandener Lied-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "999999") {
  lied(id: $id) {
    titel
    version
    rating
    art
    datum
    schlagwoerter
    kuenstler {
      name
    }
  }
}

{
  "id": "999999"
}

### Suche art von Liedern mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "Blue") {
  lieder(titel: $titel) {
        titel
    art
  }
}

{
  "titel": "Ain"
}

### Suche art, schlagwoerter und titel von Liedern mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "a") {
  lieder(titel: $titel) {
    titel
    version
    rating
    art
    datum
    schlagwoerter
    kuenstler {
      name
    }
  }
}

{
  "titel": "a"
}

### Suche art von Liedern mit NICHT-vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "Nichtvorhanden") {
  lieder(titel: $titel) {
    titel
    version
    rating
    art
    datum
    schlagwoerter
    kuenstler {
      name
    }
  }
}

{
  "titel": "Nichtvorhanden"
}
