# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    container:
      image: node:20.0.0-bullseye

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y gcc g++ make python3-minimal     
          npm install -g npm
          npm ci --omit=dev --no-package-lock --force
          npm install -D typescript@beta --no-package-lock --force
          npm audit --omit=dev fix --force
          npm install -D ts-node ts-jest typedoc --no-package-lock --force

      - name: Compile
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npx eslint

      - name: Security Audit
        run: npm audit --omit=dev

      - name: Generate Documentation
        run: |
          npx asciidoctor
          npx asciidoctor-revealjs
          npx typedoc

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            .extras/doc/entwicklerhandbuch/html
            .extras/doc/folien

      - name: Create Archive
        run: |
          rm lied.zip || true
          zip -r lied.zip dist

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lied-zip
          path: lied.zip

      - name: Build Docker Image
        run: |
          echo 'TODO: Docker-Image bauen'

      - name: Deployment for Kubernetes
        run: |
          echo 'TODO: Deployment für Kubernetes'
